export const SET_LOGIN_STATE = "SET_LOGIN_STATE";
export const SET_LOGIN_INFO = "SET_LOGIN_INFO";
export const DELETE_LOGIN_STATE = 'DELETE_LOGIN_STATE';
export const DELETE_LOGIN_INFO = 'DELETE_LOGIN_INFO'